### ISSUE TITLE
Version migrations 

### ISSUE THREAD

**Issue by sfuerte** [nozaq/terraform-aws-remote-state-s3-backend#104]
As the current release is at 1.4.0, is there any value in keeping older https://github.com/nozaq/terraform-aws-remote-state-s3-backend/blob/main/migrations.tf that specifies rules for 0.7.0? 

Trying to use `terrascan` which is not getting along with the `moved` statements at the moment (https://github.com/tenable/terrascan/issues/1262). While it still needs to be fixed on their end but wondering if it can be improved/changed from this angle also. 

Thanks a lot in advance!

**Comment by nozaq** [comment]
@sfuerte Thank you for using this module!
I'm planning to keep all historical `moved` blocks for this module following the official recommendation from the Terraform document ([the doc](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring#removing-moved-blocks)).

I guess the best workaround at this point is to fork this module and remove `migrations.tf`? This shouldn't conflict with most of future commits.

**Comment by sfuerte** [comment]
well, as the workaround we disabled hard-failing of `terrascan` for now. But thanks for the reply!
