### ISSUE TITLE
InvalidRequest: Destination bucket must have versioning enabled.

### ISSUE THREAD

**Issue by emirmandal** [nozaq/terraform-aws-remote-state-s3-backend#107]
v1.4.0
i get error when `enable_replication = true`
Error: creating S3 replication configuration for bucket (tf-remote-state...): InvalidRequest: Destination bucket must have versioning enabled.

possible reason:
Both the source and destination buckets must be versioning-enabled when you configure replication on a bucket.

proposed  solution:
file `replica.tf`
line 249

replace 
`depends_on = [aws_s3_bucket_versioning.state]`
with 
`depends_on = [aws_s3_bucket_versioning.state, aws_s3_bucket_versioning.replica]`

**Comment by booi** [comment]
I agree this is the right fix. Opened https://github.com/nozaq/terraform-aws-remote-state-s3-backend/pull/126 for this.

**Comment by nozaq** [comment]
Sorry for the delay. I just merged #126, and it's included in v1.6.1!
