### ISSUE TITLE
Dynamo Db has no deletion_protection_enabled option

### ISSUE THREAD

**Issue by darkpandarts** [nozaq/terraform-aws-remote-state-s3-backend#115]
Hi deletion_protection_enabled is not a customisable option for dynamodb. would it be possible to add this feature? :)

Many thanks!

Nice module btw!

**Comment by nozaq** [comment]
Sorry for the delay, this is fixed in v1.6.0.
Deletion protection is enabled by default, and can be turned off by setting `dynamodb_deletion_protection_enabled` variable.

**Comment by darkpandarts** [comment]
Many thanks! ⭐
