### ISSUE TITLE
[Feature Request] Add ability to disable creating IAM resources

### ISSUE THREAD

**Issue by druchoo** [nozaq/terraform-aws-remote-state-s3-backend#21]
Hello, thank you for this module. It's very useful. However, creating IAM resources is permitted in my environment. I took a go at a solution with https://github.com/nozaq/terraform-aws-remote-state-s3-backend/pull/20. Please let me know what you think.

thanks

**Comment by nozaq** [comment]
#20 got merged, and published in 0.3.0.
Sorry for the delay, thanks!
