### ISSUE TITLE
In 0.8.1/terraform 1.1.3, getting "Cross package move statement" errors

### ISSUE THREAD

**Issue by Binney** [nozaq/terraform-aws-remote-state-s3-backend#55]
Hello there! We've started receiving an error on running `terraform plan` on our project and [it looks like](https://discuss.hashicorp.com/t/error-cross-package-move-statement/33127) it might be caused by a recent ([v1.1.0](https://github.com/hashicorp/terraform/releases)) Terraform release being incompatible with your module.

```
│ Error: Cross-package move statement
│
│   on .terraform\modules\remote_state\bucket.tf line 159, in data "aws_iam_policy_document" "replica_force_ssl":
│  159:   count = var.enable_replication ? 1 : 0
│
│ This statement declares a move from an object declared in external module
│ package "registry.terraform.io/nozaq/remote-state-s3-backend/aws". Move
│ statements can be only within a single module package.
╷
│ Error: Cross-package move statement
│
│   on .terraform\modules\remote_state\bucket.tf line 188, in data "aws_region" "replica":
│  188:   count    = var.enable_replication ? 1 : 0
│
│ This statement declares a move to an object declared in external module
│ package "registry.terraform.io/nozaq/remote-state-s3-backend/aws". Move
│ statements can be only within a single module package.
```

Have you seen anything like this? If not I can try and rustle up a minimal reproduction case.

**Comment by nozaq** [comment]
@Binney Hi, it seems it's related to [an issue](https://github.com/hashicorp/terraform/pull/30333) with terraform v1.1.3. Could you try [terraform v1.1.4](https://github.com/hashicorp/terraform/releases/tag/v1.1.4) which was just released few hours ago?

**Comment by Binney** [comment]
2 days late but you're absolutely correct @nozaq , closing this issue :)
