### ISSUE TITLE
Security vulnerabilities with tfsec .

### ISSUE THREAD

**Issue by asthasrivastava48** [nozaq/terraform-aws-remote-state-s3-backend#60]
Getting security vulnerabilities with tfsec for the encryption and versioning, though we can see that all these are already enabled by default.

**Comment by nozaq** [comment]
@asthasrivastava48 In recent release of AWS provider v4.0, `aws_s3_bucket` has been quite heavily refactored, and its former configuration arguments became separate resources such as `aws_s3_bucket_logging`, `aws_s3_bucket_server_side_encryption_configuration` and `aws_s3_bucket_versioning`. 
It seems tfsec has not adopted to this update, so I suppose we can safely ignore these warnings for now.

See [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#s3-bucket-refactor) for more detail about the changes introduced in AWS provider v4.0.

**Comment by asthasrivastava48** [comment]
@nozaq I am still getting these 4 warnings.
 #1 HIGH Cluster encryption is not enabled. 
#2 MEDIUM Bucket does not have logging enabled 
 bucket.tf Lines 56-62
   56  │ resource "aws_s3_bucket" "state" {
   57  │   bucket_prefix = var.override_s3_bucket_name ? null : var.state_bucket_prefix
   58  │   bucket        = var.override_s3_bucket_name ? var.s3_bucket_name : null
   59  │   force_destroy = var.s3_bucket_force_destroy
   60  │ 
   61  │   tags = var.tags
   62  │ }
 #3 MEDIUM Bucket does not have logging enabled 
 #4 LOW Cluster encryption does not use a customer-managed KMS key. 

I am using tfsec version 1.6.2 and aws provider version 4.4.0

**Comment by nozaq** [comment]
@asthasrivastava48 Thanks for the update!

- #1 & #4: In v1.1.0, server-side encryption can be enabled for the DynamoDB table.
- #2: Bucket logging can be enabled for the state bucket via `var.s3_logging_target_bucket` argument. 
- #3: I assume this warning is for the replication bucket. Do you have a real use-case you'd like to enable logging for the replication bucket?

**Comment by asthasrivastava48** [comment]
@nozaq works fine now. Thanks
