### ISSUE TITLE
Missing IAM Permissions - Access to State Bucket and DynamoDB

### ISSUE THREAD

**Issue by Aravind04101996** [nozaq/terraform-aws-remote-state-s3-backend#74]
I am using version 1.1.0 of the module to setup backend. I am deploying terraform code through terragrunt. Getting below error when configuring backend.

For S3, "Access Denied - "s3:GetBucketVersioning" Action"

For DynamoDB, 

AccessDeniedException: User: arn:aws:sts::***:assumed-role/github-oidc-iam-assume-role/dev-deploy is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-east-2:***:table/tf-remote-state-lock

**Comment by Aravind04101996** [comment]
Fix in PR https://github.com/nozaq/terraform-aws-remote-state-s3-backend/pull/75

**Comment by nozaq** [comment]
Note: it seems that terragrunt requires `s3:GetBucketVersioning` and `dynamodb:DescribeTable` in addition to permissions necessary for default remote state usage.

https://github.com/gruntwork-io/terragrunt/issues/919
